export const condoText4 = [
  {
    title: `§ 55-79.86. Administrative agency.`,
    text: [
      `This chapter shall be administered by the Common Interest Community Board which hereinafter is called the agency.`,
    ]
  },
  {
    title: `§ 55-79.87. Exemptions from certain provisions of article.`,
    text: [
      `A. Unless the method of offer or disposition is adopted for the purpose of evasion of this chapter, the provisions of §§ 55-79.88 through 55-79.93, subsections A and C of § 55-79.94, and § 55-79.97 do not apply to:`,
      `1. Dispositions pursuant to court order;`,
      `2. Dispositions by any government or government agency;`,
      `3. Offers by the declarant on nonbinding reservation agreements;`,
      `4. Dispositions in a residential condominium in which there are three or fewer units, so long as the condominium instruments do not reserve to the declarant the right to create additional condominium units; or`,
      `5. A disposition of a unit by a sale at an auction, where a current public offering statement or resale certificate was made available as part of an auction package for prospective purchasers prior to the auction sale.`,
      `B. In cases of dispositions in a condominium where all units are restricted to nonresidential use, the provisions of §§ 55-79.88 through 55-79.95 shall not apply, unless the method of offer or disposition is adopted for the purpose of evasion of this chapter.`,
    ]
  },
  {
    title: `§ 55-79.87:1. Rental of units.`,
    text: [
      `A. Except as expressly authorized in this chapter or in the condominium instruments or as otherwise provided by law, no unit owners' association shall:`,
      `1. Condition or prohibit the rental of a unit to a tenant by a unit owner or make an assessment or impose a charge except as provided in § 55-79.42:1;`,
      `2. Charge a rental fee, application fee, or other processing fee of any kind in excess of $50 during the term of any lease;`,
      `3. Charge an annual or monthly rental fee or any other fee not expressly authorized in § 55-79.42:1;`,
      `4. Require the unit owner to use a lease or an addendum to the lease prepared by the unit owners' association;`,
      `5. Charge any deposit from the unit owner or the tenant of the unit owner; or`,
      `6. Have the authority to evict a tenant of any unit owner or to require any unit owner to execute a power of attorney authorizing the unit owners' association to so evict. However, if the unit owner designates a person licensed under the provisions of § 54.1-2106.1 as the unit owner's authorized representative with respect to any lease, the unit owners' association shall recognize such representation without a formal power of attorney, provided that the unit owners' association is given a written authorization signed by the unit owner designating such representative. Notwithstanding the foregoing, the requirements of § 55-79.77 and the condominium instruments shall be satisfied before any such representative may exercise a vote on behalf of a unit owner as a proxy.`,
      `B. The unit owners' association may require the unit owner to provide the unit owners' association with the names and contact information of the tenants and authorized occupants under such lease and any authorized agent of the unit owner, and vehicle information for such tenants or authorized occupants. The unit owners' association may require the unit owner to provide the unit owners' association with the tenant's acknowledgement of and consent to any rules and regulations of the unit owners' association.`,
      `C. The provisions of this section shall not apply to units owned by the unit owners' association.`,
    ]
  },
  {
    title: `§ 55-79.88. Limitations on dispositions of units.`,
    text: [
      `Unless exempt by § 55-79.87:`,
      `1. No declarant may offer or dispose of any interest in a condominium unit located in this Commonwealth, nor offer or dispose in this Commonwealth of any interest in a condominium unit located without this Commonwealth prior to the time the condominium including such unit is registered in accordance with this chapter.`,
      `2. No declarant may dispose of any interest in a condominium unit unless he delivers to the purchaser a current public offering statement by the time of such disposition and such disposition is expressly and without qualification or condition subject to cancellation by the purchaser within five calendar days from the contract date of the disposition or delivery of the current public offering statement, whichever is later. If the purchaser elects to cancel, he may do so by notice thereof hand-delivered or sent by United States mail, return receipt requested, to the declarant. Such cancellation shall be without penalty, and any deposit made by the purchaser shall be promptly refunded in its entirety.`,
      `3. The purchaser's right to cancel the purchase contract pursuant to subdivision 2 shall be set forth on the first page of the purchase contract in boldface print of not less than 12 point type.`,
    ]
  },
  {
    title: `§ 55-79.89. Application for registration; fee.`,
    text: [
      `A. The application for registration of the condominium shall be filed as prescribed by the agency's regulations and shall contain the following documents and information:`,
      `1. An irrevocable appointment of the agency to receive service of any lawful process in any noncriminal proceeding arising under this chapter against the applicant or his personal representative if nonresidents of the Commonwealth;`,
      `2. The states or jurisdictions in which an application for registration or similar document has been filed, and any adverse order, judgment, or decree entered in connection with the condominium by the regulatory authorities in each jurisdiction or by any court;`,
      `3. The applicant's name, address, and the form, date, and jurisdiction or organization; and the address of each of its offices in this Commonwealth;`,
      `4. The name, address, and principal occupation for the past five years of every officer of the applicant or person occupying a similar status or performing similar functions; the extent and nature of his interest in the applicant or the condominium as of a specified date within 30 days of the filing of the application;`,
      `5. A statement, in a form acceptable to the agency, of the condition of the title to the condominium project including encumbrances as of a specified date within 30 days of the date of application by a title opinion of a licensed attorney, not a salaried employee, officer or director of the applicant or owner, or by other evidence of title acceptable to the agency;`,
      `6. Copies of the instruments which will be delivered to a purchaser to evidence his interest in the unit and of the contracts and other agreements which a purchaser will be required to agree to or sign;`,
      `7. Copies of any management agreements, employment contracts or other contracts or agreements affecting the use, maintenance or access of all or a part of the condominium;`,
      `8. A statement of the zoning and other governmental regulations affecting the use of the condominium, including the site plans and building permits and their status, and also of any existing tax and existing or proposed special taxes or assessments which affect the condominium;`,
      `9. A narrative description of the promotional plan for the disposition of the units in the condominium;`,
      `10. Plats and plans of the condominium that comply with the provisions of § 55-79.58 other than the certification requirements thereof, and which show all units and buildings containing units to be built anywhere within the submitted land other than within the boundaries of any convertible lands, except that the agency may establish by regulation or order requirements in lieu of the provisions of § 55-79.58 for plats and plans of a condominium located outside this Commonwealth;`,
      `11. The proposed public offering statement;`,
      `12. Any bonds required to be posted pursuant to the provisions of this chapter; and`,
      `13. Any other information, including any current financial statement, which the agency by its regulations requires for the protection of purchasers.`,
      `B. If the declarant registers additional units to be offered for disposition in the same condominium he may consolidate the subsequent registration with any earlier registration offering units in the condominium for disposition under the same promotional plan.`,
      `C. The declarant shall immediately report any material changes in the information contained in an application for registration.`,
      `D. Each application shall be accompanied by a fee in an amount established by the agency pursuant to § 54.1-113. All fees shall be remitted by the agency to the State Treasurer, and shall be placed to the credit of the Common Interest Community Management Information Fund established pursuant to § 55-529.`,
    ]
  },
  {
    title: `§ 55-79.90. Public offering statement; condominium securities.`,
    text: [
      `A. A public offering statement shall disclose fully and accurately the characteristics of the condominium and the units therein offered and shall make known to prospective purchasers all unusual and material circumstances or features affecting the condominium. The proposed public offering statement submitted to the agency shall be in a form prescribed by its rules and regulations and shall include the following:`,
      `1. The name and principal address of the declarant and the condominium;`,
      `2. A general narrative description of the condominium stating the total number of units in the offering; the total number of units planned to be sold and rented; the total number of units that may be included in the condominium by reason of future expansion or merger of the project by the declarant;`,
      `3. Copies of the declaration and bylaws, with a brief narrative statement describing each and including information on declarant control, a projected budget for at least the first year of the condominium's operation (including projected common expense assessments for each unit), and provisions for reserves for capital expenditures and restraints on alienation;`,
      `4. Copies of any management contract, lease of recreational areas, or similar contract or agreement affecting the use, maintenance or access of all or any part of the condominium with a brief narrative statement of the effect of each such agreement upon a purchaser, and a statement of the relationship, if any, between the declarant and the managing agent or firm;`,
      `5. A general description of the status of construction, zoning, site plan approval, issuance of building permits, or compliance with any other state or local statute or regulation affecting the condominium;`,
      `6. The significant terms of any encumbrances, easements, liens and matters of title affecting the condominium;`,
      `7. The significant terms of any financing offered by the declarant to the purchaser of units in the condominium;`,
      `8. Provisions of any warranties provided by the declarant on the units and the common elements, other than the warranty prescribed by subsection B of § 55-79.79;`,
      `9. A statement that, pursuant to subdivision A 2 of § 55-79.88, the purchaser may cancel the disposition within five calendar days of delivery of the current public offering statement or within five calendar days of the contract date of the disposition, whichever is later;`,
      `10. A statement of the declarant's obligation to complete improvements of the condominium which are planned but not yet begun, or begun but not yet completed. Said statement shall include a description of the quality of the materials to be used, the size or capacity of the improvements when material, and the time by which the improvements shall be completed. Any limitations on the declarant's obligation to begin or complete any such improvements shall be expressly stated;`,
      `11. If the units in the condominium are being subjected to a time-share instrument pursuant to § 55-367, the information required to be disclosed by § 55-374;`,
      `12. A statement listing the facilities or amenities which are defined as common elements or limited common elements in the condominium instruments, which are available to a purchaser for use. Such statement shall also include whether there are any fees or other charges for the use of such facilities or amenities which are not included as part of any assessment, and the amount of such fees or charges, if any, a purchaser may be required to pay;`,
      `13. A statement of any limitation on the number of persons who may occupy a unit as a dwelling;`,
      `14. A statement setting forth any restrictions, limitation, or prohibition on the right of a unit owner to display the flag of the United States, including, but not limited to reasonable restrictions as to the size, place, and manner of placement or display of such flag; and`,
      `15. Additional information required by the agency to assure full and fair disclosure to prospective purchasers.`,
      `B. The public offering statement shall not be used for any promotional purposes before registration of the condominium project and afterwards only if it is used in its entirety. No person may advertise or represent that the agency approves or recommends the condominium or disposition thereof. No portion of the public offering statement may be underscored, italicized, or printed in larger or heavier or different color type than the remainder of the statement unless the agency requires it.`,
      `C. The agency may require the declarant to alter or amend the proposed public offering statement in order to assure full and fair disclosure to prospective purchasers, and no change in the substance of the promotional plan or plan of disposition or development of the condominium may be made after registration without notifying the agency and without making appropriate amendment of the public offering statement. A public offering statement is not current unless all amendments are incorporated.`,
      `D. If an interest in a condominium is currently registered with the Securities and Exchange Commission of the United States, a declarant satisfies all requirements relating to the preparation of a public offering statement in this chapter if he delivers to the purchaser and files with the agency a copy of the public offering statement filed with the Securities and Exchange Commission. An interest in a condominium is not a security under the provisions of the Securities Act (§ 13.1-501 et seq.).`,
    ]
  },
  {
    title: `§ 55-79.91. Inquiry and examination.`,
    text: [
      `Upon receipt of an application for registration, the agency shall conduct an examination of the material submitted to determine that:`,
      `1. The declarant can convey or cause to be conveyed the units offered for disposition if the purchaser complies with the terms of the offer;`,
      `2. There is reasonable assurance that all proposed improvements will be completed as represented;`,
      `3. The advertising material and the general promotional plan are not false or misleading and comply with the standards prescribed by the agency in its regulations and afford full and fair disclosure;`,
      `4. The declarant has not, or if a corporation, its officers, and principals have not, been convicted of a crime involving condominium unit dispositions or any aspect of the land sales business in this Commonwealth, United States, or any other state or foreign country within the past ten years and has not been subject to any injunction or administrative order restraining a false or misleading promotional plan involving land dispositions; and`,
      `5. The public offering statement requirements of this chapter have been satisfied.`,
    ]
  },
  {
    title: `§ 55-79.92. Notice of filing and registration.`,
    text: [
      `A. Upon receipt of the application for registration, the agency shall, within five business days, issue a notice of filing to the applicant. In the case of receipt of an application for a condominium that is a conversion condominium, the agency shall, within five business days, also issue a notice of filing to the chief administrative officer of the county or city in which the proposed condominium is located, which notice shall include the name and address of the applicant and the name and address or location of the proposed condominium. Within sixty days from the date of the notice of filing, the agency shall enter an order registering the condominium or rejecting the registration. If no order of rejection is entered within sixty days from the date of notice of filing, the condominium shall be deemed registered unless the applicant has consented in writing to a delay.`,
      `B. If the agency affirmatively determines, upon inquiry and examination, that the requirements of §§ 55-79.89 and 55-79.91 have been met, it shall enter an order registering the condominium and shall designate the form of the public offering statement.`,
      `C. If the agency determines upon inquiry and examination that any of the requirements of §§ 55-79.89 and 55-79.91 have not been met, the agency shall notify the applicant that the application for registration must be corrected in the particulars specified within twenty days. If the requirements are not met within the time allowed the agency shall enter an order rejecting the registration which shall include the findings of fact upon which the order is based. The order rejecting the registration shall not become effective for twenty days after issuance of the order. During this twenty-day period the applicant may petition for reconsideration and shall be entitled to a hearing or correct the particulars specified in the agency's notice. Such order of rejection shall not take effect, in any event, until such time as the hearing, once requested, is given to the applicant.`,
    ]
  },
  {
    title: `§ 55-79.93. Annual report by declarant.`,
    text: [
      `The declarant shall file a report in the form prescribed by the regulations of the agency within 30 days of each anniversary date of the order registering the condominium. The report shall reflect any material changes in information contained in the original application for registration.`,
    ]
  },
  {
    title: `§ 55-79.93:1. Annual report by unit owners' association.`,
    text: [
      `A. The unit owners' association shall file an annual report in a form and at such time as prescribed by regulations of the agency. The filing of the annual report required by this section shall commence upon the termination of the declarant control period pursuant to § 55-79.74. The annual report shall be accompanied by a fixed fee in an amount established by the agency.`,
      `B. The agency may accept copies of forms submitted to other state agencies to satisfy the requirements of this section if such forms contain substantially the same information required by the agency.`,
      `C. The unit owners' association shall also remit to the agency an annual payment as follows:`,
      `1. The lesser of:`,
      `a. $1,000 or such other amount as established by agency regulation; or`,
      `b. Five hundredths of one percent (0.05%) of the unit owners' association's gross assessment income during the preceding year.`,
      `2. For the purposes of clause b of subsection C, no minimum payment shall be less than $10.00.`,
      `D. The annual payment shall be remitted to the State Treasurer and shall be placed to the credit of the Common Interest Community Management Fund established pursuant to § 55-529.`,
    ]
  },
  {
    title: `§ 55-79.93:2. Termination of registration.`,
    text: [
      `A. In the event that all of the units in the condominium have been disposed of, and that all periods for conversion or expansion have expired, the agency shall issue an order terminating the registration of the condominium.`,
      `B. Notwithstanding any other provision of this chapter, the agency may administratively terminate the registration of a condominium if:`,
      `1. The declarant has not filed an annual report in accordance with § 55-79.93 for three or more consecutive years; or`,
      `2. The declarant's registration with the State Corporation Commission, if applicable, has not been active for five or more consecutive years.`,
    ]
  },
  {
    title: `§ 55-79.94. Conversion condominiums; special provisions.`,
    text: [
      `A. Any declarant of a conversion condominium shall include in his public offering statement in addition to the requirements of § 55-79.90 the following:`,
      `1. A specific statement of the amount of any initial or special condominium fee due from the purchaser on or before settlement of the purchase contract and the basis of such fee;`,
      `2. Information on the actual expenditures made on all repairs, maintenance, operation or upkeep of the subject building or buildings within the last three years, set forth tabularly with the proposed budget of the condominium, and cumulatively broken down on a per unit basis in proportion to the relative voting strengths allocated to the units by the bylaws. If such building or buildings have not been occupied for a period of three years, then the information shall be set forth for the maximum period such building or buildings have been occupied;`,
      `3. A description of any provisions made in the budget for reserves for capital expenditures and an explanation of the basis for such reserves, or, if no provision is made for such reserves, a statement to that effect;`,
      `4. A statement of the declarant as to the present condition of all structural components and major utility installations in the condominium, which statement shall include the approximate dates of construction, installation, and major repairs, and the expected useful life of each such item, together with the estimated cost (in current dollars) of replacing each of the same;`,
      `5. If any building included or that may be included in the condominium was substantially completed prior to July 1, 1978, a statement that each such building has been inspected for asbestos in accordance with standards in effect at the time of inspection; or that an asbestos inspection will be conducted; and whether asbestos requiring response actions has been found, and if found, that response actions have been or will be completed in accordance with applicable standards prior to the conveyance of any unit in such building. Any asbestos management program or response action undertaken by the building owner shall comply with the standards promulgated pursuant to § 2.2-1164.`,
      `B. In the case of a conversion condominium, the declarant shall give at the time specified in subsection C of this section, formal notice to each of the tenants of the building or buildings which the declarant has submitted or intends to submit to the provisions of this chapter. This notice shall advise each tenant of (i) the offering price of the unit he occupies, (ii) the projected common expense assessments against that unit for at least the first year of the condominium's operation, (iii) any relocation services or assistance, public or private, of which the declarant is aware, (iv) any measures taken or to be taken by the declarant to reduce the incidence of tenant dislocation, and (v) the details of the relocation plan, if any is provided by the declarant, to assist tenants in relocating. During the first sixty days after such notice is mailed or hand delivered, each of the said tenants shall have the exclusive right to purchase the unit he occupies, but only if such unit is to be retained in the conversion condominium without substantial alteration in its physical layout. If the conversion condominium is subject to local ordinances that have been adopted pursuant to subsections F and G, any tenant who is disabled or elderly may assign the exclusive right to purchase his unit to a government agency, housing authority, or certified nonprofit housing corporation, which shall then offer the tenant a lease at an affordable rent, following the provisions of subsection F. The acquisition of such units by the governmental agency, housing authority, or certified nonprofit housing corporation shall not (i) exceed the greater of one unit or five percent of the total number of units in the condominium or (ii) impede the condominium conversion process. In determining which, if any, units shall be acquired pursuant to this subsection, preference shall be given to elderly or disabled tenants.`,
      `The notice required above shall be hand delivered or sent by first-class mail, return receipt requested, and shall inform the tenants of the conversion to condominium. Such notice may also constitute the notice to terminate the tenancy as provided for in § 55-222, except that, despite the provisions of § 55-222, a tenancy from month to month may only be terminated upon 120 days' notice when such termination is in regard to the creation of a conversion condominium. If, however, a tenant so notified remains in possession of the unit he occupies after the expiration of the 120-day period with the permission of the declarant, in order to then terminate the tenancy, such declarant shall give the tenant a further notice as provided in § 55-222. Until the expiration of the 120-day period, the declarant shall have no right of access to the unit except as provided by subsection A of § 55-248.18 and except that, upon 45 days' written notice to the tenant, the declarant may enter the unit in order to make additional repairs, decorations, alterations or improvements, provided (i) the making of the same does not constitute an actual or constructive eviction of the tenant; and (ii) such entry is made either with the consent of the tenant or only at times when the tenant is absent from the unit. The declarant shall also provide general notice to the tenants of the condominium or proposed condominium at the time of application to the agency in addition to the formal notice required by this subsection.`,
      `C. The declarant of a conversion condominium shall, in addition to the requirements of § 55-79.89, include with the application for registration a copy of the formal notice set forth in subsection B and a certified statement that such notice, fully complying with the provisions of subsection B, shall be, at the time of the registration of such condominium, mailed or delivered to each of the tenants in the building or buildings for which registration is sought. The price and projected common expense assessments for each unit need not be filed with the agency until such notice is mailed to the tenants.`,
      `D. Notwithstanding the provisions of § 55-79.40 of this chapter, in the case of any conversion condominium created under the provisions of the Horizontal Property Act (§ 55-79.1 et seq.) for which a final report has not been issued by the agency pursuant to § 55-79.21 prior to June 1, 1975, the provisions of subsections A and B of this section shall apply and the declarant shall be required to furnish evidence of full compliance with subsections A and B prior to the issuance by the agency of a final report for such conversion condominium.`,
      `E. Any county, city or town may require by ordinance that the declarant of a conversion condominium file with that governing body all information which is required by the agency pursuant to § 55-79.89 and a copy of the formal notice required by subsection B. Such information shall be filed with that governing body when the application for registration is filed with the agency, and such copy of the formal notice shall be filed with that governing body. There shall be no fees for such filings.`,
      `F. The governing body of any county, city or town may enact an ordinance requiring that elderly or disabled tenants occupying as their residence, at the time of issuance of the general notice required by subsection B, apartments or units in a conversion condominium be offered leases or extensions of leases on the apartments or units they then occupied, or on other apartments or units of at least equal size and overall quality. The terms and conditions thereof shall be as agreed upon by the lessor and the lessee, provided that the rent for such apartment or unit shall not be in excess of reasonable rent for comparable apartments or units in the same market area as such conversion condominium and such lease shall include or incorporate by reference the bylaws and/or rules and regulations, if any, of the association. No such ordinance may require that such leases or extensions be offered on more than twenty percent of the apartments or units in such conversion condominium, nor may any such ordinance require that such leases or extensions extend beyond three years from the date of such notice. Such leases or extensions shall not be required, however, in the case of any apartments or units which will, in the course of the conversion, be substantially altered in the physical layout, restricted exclusively to nonresidential use, or be converted in such a manner as to require relocation of the tenant in premises outside of the project being converted.`,
      `For the purposes of this section:`,
      `"Affordable rent" means a monthly rent that does not exceed the greater of 30 percent of the annual gross income of the tenant household or 30 percent of the imputed income limit applicable to such unit size, as published by the Virginia Housing Development Authority for compliance with the Low Income Housing Tax Credit program.`,
      `"Certified nonprofit housing corporation" means a nonprofit organization exempt from taxation under § 501(c) (3) of the Internal Revenue Code that has been certified by a locality as actively engaged in producing or preserving affordable housing as determined by criteria established by the locality.`,
      `"Disabled" means a person suffering from a severe, chronic physical or mental impairment which results in substantial functional limitations.`,
      `"Elderly" means a person not less than 62 years of age.`,
      `G. The governing body of any county utilizing the urban county executive form of optional government (§§ 15.2-800 through 15.2-858) or the county manager plan of optional government (§§ 15.2-702 through 15.2-749), or of any city or town adjoining any such county, may require by ordinance that the declarant of any residential condominium converted from multi-family rental use shall reimburse any tenant displaced by the conversion for amounts actually expended to relocate as a result of such dislocation. The reimbursement shall not be required to exceed the amount which the tenant would have been entitled to receive under §§ 25.1-407 and 25.1-415 if the real estate comprising the condominium had been condemned by the Department of Transportation.`,
    ]
  },
  {
    title: `§ 55-79.95. Escrow of deposits.`,
    text: [
      `A. Any deposit made in regard to any disposition of a unit, including a nonbinding reservation agreement, shall be held in escrow until delivered at settlement. Such escrow funds shall be deposited in a separate account designated for this purpose which is federally insured and located in Virginia; except where such deposits are being held by a real estate broker or attorney licensed under the laws of this Commonwealth such funds may be placed in that broker's or attorney's regular escrow account and need not be placed in a separate designated account. Such escrow funds shall not be subject to attachment by the creditors of either the purchaser or the declarant.`,
      `B. In lieu of escrowing deposits as provided in subsection A, the declarant of a condominium consisting of more than 50 units may:`,
      `1. Obtain and maintain a corporate surety bond issued by a surety authorized to do business in the Commonwealth, in the form and amount set forth below, or`,
      `2. Obtain and maintain an irrevocable letter of credit issued by a financial institution whose accounts are insured by the FDIC, in the form and amount set forth below.`,
      `The surety bond or letter of credit shall be maintained until (i) the granting of a deed to the unit, (ii) the purchaser's default under a purchase contract for the unit entitling the declarant to retain the deposit, or (iii) the refund of the deposit to the purchaser, whichever occurs first.`,
      `C. The surety bond shall be payable to the Commonwealth for the use and benefit of every person protected under the provisions of this chapter. The declarant shall file the bond with the Common Interest Community Board. The surety bond may be either in the form of an individual bond for each deposit accepted by the declarant or, if the total amount of the deposits accepted by the declarant under this chapter exceeds $10,000, it may be in the form of a blanket bond. If the bond is a blanket bond, the amount shall be as follows. If the amount of such deposits is:`,
      `1. $75,000 or less, the blanket bond shall be $75,000;`,
      `2. More than $75,000 but less than $200,000, the blanket bond shall be $200,000;`,
      `3. $200,000 or more but less than $500,000, the blanket bond shall be $500,000;`,
      `4. $500,000 or more but less than $1 million, the blanket bond shall be $1 million; and`,
      `5. $1 million or more, the blanket bond shall be 100 percent of the amount of such deposits.`,
      `D. The letter of credit shall be payable to the Commonwealth for use and benefit of every person protected under this chapter. The declarant shall file the letter of credit with the Common Interest Community Board. The letter of credit may be either in the form of an individual letter of credit for each deposit accepted by the declarant or, if the total amount of the deposits accepted by the declarant under this chapter exceeds $10,000, it may be in the form of a blanket letter of credit. If the letter of credit is a blanket letter of credit, the amount shall be as follows. If the amount of such deposits is:`,
      `1. $75,000 or less, the blanket letter of credit shall be $75,000;`,
      `2. More than $75,000 but less than $200,000, the blanket letter of credit shall be $200,000;`,
      `3. $200,000 or more but less than $500,000, the blanket letter of credit shall be $500,000;`,
      `4. $500,000 or more but less than $1 million, the blanket letter of credit shall be $1 million; and`,
      `5. $1 million or more, the blanket letter of credit shall be 100 percent of the amount of such deposits.`,
      `For the purposes of determining the amount of any blanket letter of credit that a declarant maintains in any calendar year, the total amount of deposits considered held by the declarant shall be determined as of May 31 in each calendar year and the amount of the letter of credit shall be in accordance with the amount of deposits held as of May 31.`,
    ]
  },
  {
    title: `§ 55-79.96. Declarant to deliver declaration, etc., to purchaser.`,
    text: [
      `The declarant shall within ten days of recordation of the condominium instruments as provided for in §§ 55-79.45 and 55-79.49 hereof, forward to each purchaser at his last known address by first-class mail, return receipt requested, an exact copy of the recorded declaration and bylaws.`,
    ]
  },
  {
    title: `§ 55-79.97. Resale by purchaser; resale certificate; use of for sale sign in connection with resale; designation of authorized representative.`,
    text: [
      `A. In the event of any resale of a condominium unit by a unit owner other than the declarant, and subject to the provisions of subsection F and § 55-79.87 A, the unit owner shall disclose in the contract that (i) the unit is located within a development which is subject to the Condominium Act, (ii) the Act requires the seller to obtain from the unit owners' association a resale certificate and provide it to the purchaser, (iii) the purchaser may cancel the contract within three days after receiving the resale certificate or being notified that the resale certificate will not be available, (iv) if the purchaser has received the resale certificate, the purchaser has a right to request a resale certificate update or financial update in accordance with § 55-79.97:1, as appropriate, and (v) the right to receive the resale certificate and the right to cancel the contract are waived conclusively if not exercised before settlement.`,
      `For purposes of clause (iii), the resale certificate shall be deemed not to be available if (a) a current annual report has not been filed by the unit owners' association with either the State Corporation Commission pursuant to § 13.1-936 or the Common Interest Community Board pursuant to § 55-79.93:1, (b) the seller has made a written request to the unit owners' association that the resale certificate be provided and no such resale certificate has been received within 14 days in accordance with subsection C, or (c) written notice has been provided by the unit owners' association that a resale certificate is not available.`,
      `B. If the contract does not contain the disclosure required by subsection A, the purchaser's sole remedy is to cancel the contract prior to settlement.`,
      `C. The information contained in the resale certificate shall be current as of a date specified on the resale certificate. A resale certificate update or a financial update may be requested as provided in § 55-79.97:1, as appropriate. The purchaser may cancel the contract (i) within three days after the date of the contract, if the purchaser receives the resale certificate or is notified that the resale certificate will not be available on or before the date that the purchaser signs the contract; (ii) within three days after receiving the resale certificate if the resale certificate or notice that the resale certificate will not be available is hand delivered, delivered by electronic means, or delivered by a commercial overnight delivery service or the United States Postal Service, and a receipt obtained; or (iii) within six days after the postmark date if the resale certificate or notice that the resale certificate will not be available is sent to the purchaser by United States mail. The purchaser may also cancel the contract at any time prior to settlement if the purchaser has not been notified that the resale certificate will not be available and the resale certificate is not delivered to the purchaser.`,
      `Notice of cancellation shall be provided to the unit owner or his agent by one of the following methods:`,
      `a. Hand delivery;`,
      `b. United States mail, postage prepaid, provided the sender retains sufficient proof of mailing, which may be either a United States postal certificate of mailing or a certificate of service prepared by the sender confirming such mailing;`,
      `c. Electronic means provided the sender retains sufficient proof of the electronic delivery, which may be an electronic receipt of delivery, a confirmation that the notice was sent by facsimile, or a certificate of service prepared by the sender confirming the electronic delivery; or`,
      `d. Overnight delivery using a commercial service or the United States Postal Service.`,
      `In the event of a dispute, the sender shall have the burden to demonstrate delivery of the notice of cancellation. Such cancellation shall be without penalty, and the unit owner shall cause any deposit to be returned promptly to the purchaser.`,
      `A resale certificate shall include the following:`,
      `1. An appropriate statement pursuant to subsection H of § 55-79.84 which need not be notarized and, if applicable, an appropriate statement pursuant to § 55-79.85;`,
      `2. A statement of any expenditure of funds approved by the unit owners' association or the executive organ which shall require an assessment in addition to the regular assessment during the current or the immediately succeeding fiscal year;`,
      `3. A statement, including the amount, of all assessments and any other fees or charges currently imposed by the unit owners' association, together with any known post-closing fee charged by the common interest community manager, if any, and associated with the purchase, disposition and maintenance of the condominium unit and the use of the common elements, and the status of the account;`,
      `4. A statement whether there is any other entity or facility to which the unit owner may be liable for fees or other charges;`,
      `5. The current reserve study report or a summary thereof, a statement of the status and amount of any reserve or replacement fund and any portion of the fund designated for any specified project by the executive organ;`,
      `6. A copy of the unit owners' association's current budget or a summary thereof prepared by the unit owners' association and a copy of the statement of its financial position (balance sheet) for the last fiscal year for which a statement is available, including a statement of the balance due of any outstanding loans of the unit owners' association;`,
      `7. A statement of the nature and status of any pending suits or unpaid judgments to which the unit owners' association is a party which either could or would have a material impact on the unit owners' association or the unit owners or which relates to the unit being purchased;`,
      `8. A statement setting forth what insurance coverage is provided for all unit owners by the unit owners' association, including the fidelity bond maintained by the unit owners' association, and what additional insurance coverage would normally be secured by each individual unit owner;`,
      `9. A statement that any improvements or alterations made to the unit, or the limited common elements assigned thereto, are or are not in violation of the condominium instruments;`,
      `10. A copy of the current bylaws, rules and regulations and architectural guidelines adopted by the unit owners' association and the amendments thereto;`,
      `11. A statement of whether the condominium or any portion thereof is located within a development subject to the Property Owners' Association Act (§ 55-508 et seq.) of Chapter 26 of this title;`,
      `12. A copy of the notice given to the unit owner by the unit owners' association of any current or pending rule or architectural violation;`,
      `13. A copy of any approved minutes of the executive organ and unit owners' association meetings for the six calendar months preceding the request for the resale certificate;`,
      `14. Certification that the unit owners' association has filed with the Common Interest Community Board the annual report required by § 55-79.93:1; which certification shall indicate the filing number assigned by the Common Interest Community Board and the expiration date of such filing;`,
      `15. A statement of any limitation on the number of persons who may occupy a unit as a dwelling;`,
      `16. A statement setting forth any restrictions, limitation or prohibition on the right of a unit owner to display the flag of the United States, including, but not limited to reasonable restrictions as to the size, time, place, and manner of placement or display of such flag;`,
      `17. A statement setting forth any restriction, limitation, or prohibition on the right of a unit owner to install or use solar energy collection devices on the unit owner's property;`,
      `18. A statement indicating any known project approvals currently in effect issued by secondary mortgage market agencies; and`,
      `19. A copy of the fully completed form developed by the Common Interest Community Board pursuant to § 54.1-2350.`,
      `Failure to receive a resale certificate shall not excuse any failure to comply with the provisions of the condominium instruments, articles of incorporation, or rules or regulations.`,
      `The resale certificate shall be delivered in accordance with the written request and instructions of the seller or the seller's authorized agent, including whether the resale certificate shall be delivered electronically or in hard copy, at the option of the seller or the seller's authorized agent, and shall specify the complete contact information for the parties to whom the resale certificate shall be delivered. The resale certificate shall be delivered within 14 days of receipt of such request. The resale certificate shall not, in and of itself, be deemed a security within the meaning of § 13.1-501.`,
      `D. The seller or the seller's authorized agent may request that the resale certificate be provided in hard copy or in electronic form. A unit owners' association or common interest community manager may provide the resale certificate electronically; however, the seller or the seller's authorized agent shall have the right to request that the resale certificate be provided in hard copy. The seller or the seller's authorized agent shall continue to have the right to request a hard copy of the resale certificate in person at the principal place of business of the unit owners' association. If the seller or the seller's authorized agent requests that the resale certificate be provided in electronic format, neither the unit owners' association nor its common interest community manager may require the seller or the seller's authorized agent to pay any fees to use the provider's electronic network or system. The resale certificate shall not be delivered in hard copy if the requester has requested delivery of such resale certificate electronically. If the resale certificate is provided electronically by a website link, the preparer shall not cause the website link to expire within the subsequent 90-day period. The preparer shall not charge another fee during the subsequent 12-month period, except that the preparer may charge an update fee for a financial update or for an inspection as provided in § 55-79.97:1. If the seller or the seller's authorized agent asks that the resale certificate be provided in electronic format, the seller or the seller's authorized agent may request that an electronic copy be provided to each of the following named in the request: the seller, the seller's authorized agent, the purchaser, the purchaser's authorized agent, and not more than one other person designated by the requester. If so requested, the unit owners' association or its common interest community manager may require the seller or the seller's authorized agent to pay the fee specified in § 55-79.97:1. Regardless of whether the resale certificate is delivered in paper form or electronically, the preparer of the resale certificate shall provide such resale certificate directly to the persons designated by the requester to the addresses or, if applicable, the email addresses provided by the requester.`,
      `E. Subject to the provisions of § 55-79.87, but notwithstanding any other provisions of this chapter, the provisions and requirements of this section shall apply to any such resale of a condominium unit created under the provisions of the Horizontal Property Act (§ 55-79.1 et seq.).`,
      `F. The resale certificate required by this section need not be provided in the case of:`,
      `1. A disposition of a unit by gift;`,
      `2. A disposition of a unit pursuant to court order if the court so directs;`,
      `3. A disposition of a unit by foreclosure or deed in lieu of foreclosure; or`,
      `4. A disposition of a unit by a sale at auction, when the resale certificate was made available as part of the auction package for prospective purchasers prior to the auction.`,
      `G. In any transaction in which a resale certificate is required and a trustee acts as the seller in the sale or resale of a unit, the trustee shall obtain the resale certificate from the unit owners' association and provide the resale certificate to the purchaser.`,
      `H. For purposes of this chapter:`,
      `"Delivery" means that the resale certificate is delivered to the purchaser or purchaser's authorized agent by one of the methods specified in this section.`,
      `"Purchaser's authorized agent" means any person designated by such purchaser in a ratified real estate contract for purchase and sale of residential real property or other writing designating such agent.`,
      `"Receives, received, or receiving" the resale certificate means that the purchaser or purchaser's authorized agent has received the resale certificate by one of the methods specified in this section.`,
      `"Seller's authorized agent" means a person designated by such seller in a ratified real estate contract for purchase and sale of residential real property or other writing designating such agent.`,
      `I. Unless otherwise provided in the ratified real estate contract or other writing, delivery to the purchaser's authorized agent shall require delivery to such agent and not to a person other than such agent. Delivery of the resale certificate may be made by the unit owner or the seller's authorized agent.`,
      `J. If the unit is governed by more than one association, the purchaser's right of cancellation may be exercised within the required time frames following delivery of the last resale certificate or disclosure packet.`,
      `K. Except as expressly authorized in this chapter or in the condominium instruments or as otherwise provided by law, no unit owners' association shall:`,
      `1. Require the use of any for sale sign that is (i) a unit owners' association sign or (ii) a real estate sign that does not comply with the requirements of the Virginia Real Estate Board. A unit owners' association may, however, prohibit the placement of signs in the common elements and establish reasonable rules and regulations that regulate (a) the number of real estate signs to be located on real property upon which the owner has a separate ownership interest or a right of exclusive possession, so long as at least one real estate sign is permitted; (b) the geographical location of real estate signs on real property in which the owner has a separate ownership interest or a right of exclusive possession, so long as the location of the real estate signs complies with the requirements of the Virginia Real Estate Board; (c) the manner in which real estate signs are affixed to real property; and (d) the period of time after settlement when the real estate signs on such real property shall be removed; or`,
      `2. Require any unit owner to execute a formal power of attorney if the unit owner designates a person licensed under the provisions of § 54.1-2106.1 as the unit owner's authorized representative, and the unit owners' association shall recognize such representation without a formal power of attorney, provided that the unit owners' association is given a written authorization signed by the unit owner designating such representative. Notwithstanding the foregoing, the requirements of § 55-79.77 and the condominium instruments shall be satisfied before any such representative may exercise a vote on behalf of a unit owner as a proxy.`,
    ]
  },
  {
    title: `§ 55-79.97:1. Fees for resale certificate.`,
    text: [
      `A. The unit owners' association may charge fees as authorized by this section for the inspection of the property, the preparation and issuance of the resale certificate required by § 55-79.97, and for such other services as are set out in this section. Nothing in this chapter shall be construed to authorize the unit owners' association or common interest community manager to charge an inspection fee for a unit except as provided in this section.`,
      `B. A reasonable fee may be charged by the preparer of the resale certificate as follows for:`,
      `1. The inspection of the unit, as authorized in the declaration and as required to prepare the resale certificate, a fee not to exceed $100;`,
      `2. The preparation and delivery of the resale certificate in (i) paper format, a fee not to exceed $150 for no more than two hard copies, or (ii) electronic format, a fee not to exceed a total of $125, for an electronic copy to each of the following named in the request: the seller, the seller's authorized agent, the purchaser, the purchaser's authorized agent, and not more than one other person designated by the requester. Only one fee shall be charged for the preparation and delivery of the resale certificate;`,
      `3. At the option of the seller or the seller's authorized agent, with the consent of the unit owners' association or the common interest community manager, expediting the inspection, preparation, and delivery of the resale certificate, an additional expedite fee not to exceed $50;`,
      `4. At the option of the seller or the seller's authorized agent, an additional hard copy of the resale certificate, a fee not to exceed $25 per hard copy;`,
      `5. At the option of the seller or the seller's authorized agent, a fee not to exceed an amount equal to the actual cost paid to a third-party commercial delivery service for hand delivery or overnight delivery of the resale certificate; and`,
      `6. A post-closing fee to the purchaser of the unit, collected at settlement, for the purpose of establishing the purchaser as the owner of the unit in the records of the unit owners' association, a fee not to exceed $50.`,
      `Neither the unit owners' association nor its common interest community manager shall require cash, check, certified funds, or credit card payments at the time the request for the resale certificate is made. The resale certificate shall state that all fees and costs for the resale certificate shall be the personal obligation of the unit owner and shall be an assessment against the unit and collectible as any other assessment in accordance with the provisions of the condominium instruments and § 55-79.83, if not paid at settlement or within 60 days of the delivery of the resale certificate, whichever occurs first.`,
      `For purposes of this section, an expedite fee shall only be charged if the inspection and preparation of delivery of the resale certificate are completed within five business days of the request for a resale certificate.`,
      `C. No fees other than those specified in this section, and as limited by this section, shall be charged by the unit owners' association or its common interest community manager for compliance with the duties and responsibilities of the unit owners' association under this section. No additional fee shall be charged for access to the unit owners' association's or common interest community manager's website. The unit owners' association or its common interest community manager shall publish and make available in paper or electronic format, or both, a schedule of the applicable fees so that the seller or the seller's authorized agent will know such fees at the time of requesting the resale certificate.`,
      `D. Any fees charged pursuant to this section shall be collected at the time settlement occurs on the sale of the unit and shall be due and payable out of the settlement proceeds in accordance with this section. The seller shall be responsible for all costs associated with the preparation and delivery of the resale certificate, except for the costs of any resale certificate update or financial update, which costs shall be the responsibility of the requester, payable at settlement. The settlement agent shall escrow a sum sufficient to pay such costs at settlement. Neither the unit owners' association nor its common interest community manager shall require cash, check, certified funds, or credit card payments at the time the request is made for the resale certificate.`,
      `E. If settlement does not occur within 60 days of the delivery of the resale certificate, or funds are not collected at settlement and disbursed to the unit owners' association or the common interest community manager, all fees, including those costs that would have otherwise been the responsibility of the purchaser or settlement agent, shall be (i) assessed within one year after delivery of the resale certificate against the unit owner, (ii) the personal obligation of the unit owner, and (iii) an assessment against the unit and collectible as any other assessment in accordance with the provisions of the condominium instruments and § 55-79.83. The seller may pay the unit owners' association by cash, check, certified funds, or credit card, if credit card payment is an option offered by the unit owners' association. The unit owners' association shall pay the common interest community manager the amount due from the unit owner within 30 days after invoice.`,
      `F. The maximum allowable fees charged in accordance with this section shall adjust every five years, as of January 1 of that year, in an amount equal to the annual increases for that five-year period in the United States Average Consumer Price Index for all items, all urban consumers (CPI-U), as published by the Bureau of Labor Statistics of the U.S. Department of Labor.`,
      `G. If a resale certificate has been issued within the preceding 12-month period, a person specified in the written instructions of the seller or the seller's authorized agent, including the seller or the seller's authorized agent or the purchaser or the purchaser's authorized agent, may request a resale certificate update. The requester shall specify whether the resale certificate update shall be delivered electronically or in hard copy and shall specify the complete contact information of the parties to whom the update shall be delivered. The resale certificate update shall be delivered within 10 days of the written request.`,
      `H. The settlement agent may request a financial update. The requester shall specify whether the financial update shall be delivered electronically or in hard copy and shall specify the complete contact information of the parties to whom the update shall be delivered. The financial update shall be delivered within three business days of the written request.`,
      `I. A reasonable fee for the resale certificate update or financial update may be charged by the preparer, not to exceed $50. At the option of the purchaser or the purchaser's authorized agent, the requester may request that the unit owners' association or the common interest community manager perform an additional inspection of the unit, as authorized in the declaration, for a fee not to exceed $100. Any fees charged for the specified update shall be collected at the time settlement occurs on the sale of the property. The settlement agent shall escrow a sum sufficient to pay such costs at settlement. Neither the unit owners' association nor its common interest community manager, if any, shall require cash, check, certified funds, or credit card payments at the time the request is made for the resale certificate update. The requester may request that the specified update be provided in hard copy or in electronic form.`,
      `J. No unit owners' association or common interest community manager may require the requester to request the specified update electronically. The seller or the seller's authorized agent shall continue to have the right to request a hard copy of the specified update in person at the principal place of business of the unit owners' association. If the requester asks that the specified update be provided in electronic format, neither the unit owners' association nor its common interest community manager may require the requester to pay any fees to use the provider's electronic network or system. A copy of the specified update shall be provided to the seller or the seller's authorized agent.`,
      `K. When a resale certificate has been delivered as required by § 55-79.97, the unit owners' association shall, as to the purchaser, be bound by the statements set forth therein as to the status of the assessment account and the status of the unit with respect to any violation of the condominium instruments as of the date of the statement unless the purchaser had actual knowledge that the contents of the resale certificate were in error.`,
      `L. If the unit owners' association or its common interest community manager has been requested in writing to furnish the resale certificate required by § 55-79.97, failure to provide the resale certificate substantially in the form provided in this section shall be deemed a waiver of any claim for delinquent assessments or of any violation of the declaration, bylaws, rules and regulations, or architectural guidelines existing as of the date of the request with respect to the subject unit. The preparer of the resale certificate shall be liable to the seller in an amount equal to the actual damages sustained by the seller in an amount not to exceed $1,000. The purchaser shall nevertheless be obligated to abide by the condominium instruments, rules and regulations, and architectural guidelines of the unit owners' association as to all matters arising after the date of the settlement of the sale.`,
      `M. The Common Interest Community Board may assess a monetary penalty for failure to deliver the resale certificate within 14 days against any (i) unit owners' association pursuant to § 54.1-2351 or (ii) common interest community manager pursuant to § 54.1-2349 and regulations promulgated thereto, and may issue a cease and desist order pursuant to § 54.1-2349 or 54.1-2352, as applicable.`,
    ]
  },
  {
    title: `§ 55-79.97:2. Properties subject to more than one declaration.`,
    text: [
      `If the unit is subject to more than one declaration, the unit owners' association or its common interest community manager may charge the fee authorized by § 55-79.97:1 for each of the applicable associations, provided however, that no association may charge an inspection fee unless the association has architectural control over the unit.`,
    ]
  },
  {
    title: `§ 55-79.97:3. Requests by settlement agents.`,
    text: [
      `A. The settlement agent may request a financial update from the preparer of the resale certificate. The preparer of the resale certificate shall, upon request from the settlement agent, provide the settlement agent with written escrow instructions directing the amount of any funds to be paid from the settlement proceeds to the association or the common interest community manager. There shall be no fees charged for a response by the association or its common interest community manager to a request from the settlement agent for written escrow instructions; however a fee may be charged for a financial update pursuant to this chapter.`,
      `B. The settlement agent, when transmitting funds to the unit owners' association or the common interest community manager, shall, unless otherwise directed in writing, provide the preparer of the resale certificate with (i) the complete record name of the seller, (ii) the address of the subject unit, (iii) the complete name of the purchaser, (iv) the date of settlement, and (v) a brief explanation of the application of any funds transmitted or by providing a copy of a settlement statement, unless otherwise prohibited.`,
    ]
  },
  {
    title: `§ 55-79.98. General powers and duties of the Common Interest Community Board.`,
    text: [
      `A. The agency shall prescribe reasonable rules and regulations which shall be adopted, amended or repealed in compliance with law applicable to the administrative procedure of agencies of government. The rules and regulations shall include but not be limited to provisions for advertising standards to assure full and fair disclosure; provisions for operating procedures; and other rules and regulations as are necessary and proper to accomplish the purpose of this chapter.`,
      `B. The agency by rule or by an order, after reasonable notice and hearing, may require the filing of advertising material relating to condominiums prior to its distribution.`,
      `C. If it appears that a person has engaged or is about to engage in an act or practice constituting a violation of a provision of this chapter, or a rule or order hereunder, the agency, with or without prior administrative proceedings may bring an action in the circuit court of the city or county in which any portion of the condominium is located to enjoin the acts or practices and to enforce compliance with this chapter or any rule or order hereunder. Upon proper showing, injunctive relief of temporary restraining orders shall be granted. The agency is not required to post a bond in any court proceedings or prove that any other adequate remedy at law exists.`,
      `D. With respect to any lawful process served upon the agency pursuant to the appointment made in accordance with subdivision A 1 of § 55-79.89, the agency shall forthwith cause the same to be sent by registered or certified mail to any of the principals, officers, directors, partners, or trustees of the declarant listed in the application for registration at the last address listed in such application or any annual report.`,
      `E. The agency may intervene in any suit involving the declarant. In any suit by or against a declarant involving a condominium, the declarant shall promptly furnish the agency notice of the suit and copies of all pleadings.`,
      `F. The agency may:`,
      `1. Accept registrations filed in other states or with the federal government;`,
      `2. Contract with similar agencies in this Commonwealth or other jurisdictions to perform investigative functions;`,
      `3. Accept grants in aid from any governmental source.`,
      `G. The agency shall cooperate with similar agencies in other jurisdictions to establish uniform filing procedures and forms, uniform public offering statements, advertising standards, rules and common administrative practices.`,
    ]
  },
  {
    title: `§ 55-79.99. Investigations and proceedings.`,
    text: [
      `A. Whenever the agency receives a written complaint which appears to state a valid claim, the agency shall make necessary public or private investigations in accordance with law within or outside of this Commonwealth to determine whether any declarant, its agents, employees or other representatives have violated or are about to violate this chapter or any rule or order hereunder, or to aid in the enforcement of this chapter or in the prescribing of rules, regulations and forms hereunder. The agency may also in like manner and with like authority investigate written complaints against persons other than the declarant, its agents, employees or other representatives.`,
      `B. For the purpose of any investigation or proceeding under this chapter, the agency or any officer designated by rule may administer oaths or affirmations, and upon its own motion or upon request of any party shall subpoena witnesses, compel their attendance, take evidence, and require the production of any matter which is relevant to the investigation, including the existence, description, nature, custody, condition, and location of any books, documents, or other tangible things and the identity and location of persons having knowledge of relevant facts or any other matter reasonably calculated to lead to the discovery of material evidence.`,
      `C. Upon failure to obey a subpoena or to answer questions propounded by the investigating officer and upon reasonable notice to all persons affected thereby, the agency may apply to the Circuit Court of the City of Richmond for an order compelling compliance.`,
    ]
  },
  {
    title: `§ 55-79.100. Cease and desist orders.`,
    text: [
      `(a) If the agency determines after notice and hearing that a person has:`,
      `(1) Violated any provision of this chapter;`,
      `(2) Directly or through an agent or employee knowingly engaged in any false, deceptive, or misleading advertising, promotional, or sales methods to offer or dispose of a unit;`,
      `(3) Made any substantial change in the plan of disposition and development of the condominium subsequent to the order of registration without notifying the agency;`,
      `(4) Disposed of any units which have not been registered with the agency; or`,
      `(5) Violated any lawful order or rule of the agency;`,
      `it may issue an order requiring the person to cease and desist from the unlawful practice and to take such affirmative action as in the judgment of the agency will carry out the purposes of this chapter.`,
      `(b) If the agency makes a finding of fact in writing that the public interest will be irreparably harmed by delay in issuing an order, it may issue a temporary cease and desist order. Prior to issuing the temporary cease and desist order, the agency shall give notice of the proposal to issue a temporary cease and desist order to the person. Every temporary cease and desist order shall include in its terms a provision that upon request a hearing will be held promptly to determine whether or not it becomes permanent.`,
    ]
  },
  {
    title: `§ 55-79.101. Revocation of registration.`,
    text: [
      `(a) A registration may be revoked after notice and hearing upon a written finding of fact that the declarant has:`,
      `(1) Failed to comply with the terms of a cease and desist order;`,
      `(2) Been convicted in any court subsequent to the filing of the application for registration for a crime involving fraud, deception, false pretenses, misrepresentation, false advertising, or dishonest dealing in real estate transactions;`,
      `(3) Disposed of, concealed, or diverted any funds or assets of any person so as to defeat the rights of unit purchasers;`,
      `(4) Failed faithfully to perform any stipulation or agreement made with the agency as an inducement to grant any registration, to reinstate any registration, or to approve any promotional plan or public offering statement; or`,
      `(5) Made intentional misrepresentations or concealed material facts in an application for registration.`,
      `Findings of fact, if set forth in statutory language, shall be accompanied by concise and explicit statement of the underlying facts supporting the findings.`,
      `(b) If the agency finds after notice and hearing that the developer has been guilty of a violation for which revocation could be ordered, it may issue a cease and desist order instead.`,
    ]
  },
  {
    title: `§ 55-79.102. Judicial review.`,
    text: [
      `Proceedings for judicial review shall be in accordance with the provisions of the Administrative Process Act (§ 2.2-4000 et seq.).`,
    ]
  },
  {
    title: `§ 55-79.103. Penalties.`,
    text: [
      `Any person who willfully violates any provision of §§ 55-79.87, 55-79.88, 55-79.89, 55-79.90, 55-79.93, 55-79.94, 55-79.95, or any rule adopted under or order issued pursuant to § 55-79.98, or any person who willfully in an application for registration makes any untrue statement of a material fact or omits to state a material fact shall be guilty of a misdemeanor and may be fined not less than $1,000 or double the amount of gain from the transaction, whichever is the larger but not more than $50,000; or he may be imprisoned for not more than 6 months; or both, for each offense.`,
    ]
  }
];
